### ISSUE TITLE
Está rodando em algum endereço da Internet?

### ISSUE THREAD

**Issue by alexandre-mbm** [codigourbano/cidades-comestiveis#1]

**Comment by vgeorge** [comment]
Ainda não, a aplicação está em desenvolvimento.

**Comment by alexandre-mbm** [comment]
Quando estiver, sugiro que o link seja colocado no cabeçalho deste repositório.

**Comment by vgeorge** [comment]
Pode deixar! Abraço

**Comment by alexandre-mbm** [comment]
Que tal deixar a issue aberta, pra avisar quem estiver escrito nela?
