### ISSUE TITLE
Máscara Divisão Subprefeituras

### ISSUE THREAD

**Issue by andrebiazoti** [codigourbano/cidades-comestiveis#22]
Muitas questões relacionadas à horta comunitária são resolvidas via Subprefeituras e as pessoas desconhecem em que subprefeitura estão.

Vocês acham que seria interessante colocar uma máscara no mapa para divisão por subprefeituras? (se não me engano, tinha um mapa dos MapasColetivos que tinha essa máscara)

**Comment by vgeorge** [comment]
@andrebiazoti: Agora não é possível desenvolver filtros a partir de subprefeituras. Você está propondo apenas um recurso visual do mapa? Podemos tentar fazer assim, mas esta funcionalidade teria uma prioridade baixa porque há outras mais importantes a serem resolvidas e não sabemos se vai ficar um mapa muito poluído.

**Comment by andrebiazoti** [comment]
Tranquilo, vamos deixar isso de lado então.
