### ISSUE TITLE
Fotos para iniciativas

### ISSUE THREAD

**Issue by vgeorge** [codigourbano/cidades-comestiveis#26]
Adicionar esta funcionalidade vai requerer uma mudança relevante no cliente e no servidor, minha proposta é deixar para uma próxima etapa da plataforma.

**Comment by miguelpeixe** [comment]
O que seria essa imagem exatamente? Seria o logo da iniciativa?

No atual conceito de inciativa, ela é uma entidade que pode se relacionar com um terreno. Ela não é um terreno por si só nem uma pessoa necessariamente (para ter foto de perfil)

**Comment by andrebiazoti** [comment]
Ok, podemos deixar de lado então.
A ideia era inserir uma foto das hortas já existentes. Talvez um logo, caso a iniciativa tenha. Mas podemos deixar isso para um próximo momento.
