### ISSUE TITLE
Botão de editar não funciona

### ISSUE THREAD

**Issue by vgeorge** [codigourbano/cidades-comestiveis#35]
Comentário do @andrebiazoti:

> No Meus Compartilhamentos, o botão de editar aparece quando coloco o mouse sobre o item, mas não funciona. Apenas quando eu clico sobre o item é que abre a janela de edição. É interessante que esse botão de edição funcione tbm.

**Comment by andrebiazoti** [comment]
O botãozinho de editar ainda não funciona. Ele aparece, mas não tem funcionalidade. Só quando eu clico no título do recurso é que ele abre para edição.
