### ISSUE TITLE
Deletar inserções-teste

### ISSUE THREAD

**Issue by andrebiazoti** [codigourbano/cidades-comestiveis#48]
É preciso deletar todas as inserções teste que foram feitas antes do lançamento da plataforma no domingo. Pode incluir todas as minhas.

**Comment by vgeorge** [comment]
O banco de dados foi reiniciado.

**Comment by andrebiazoti** [comment]
:-D

Em 4 de julho de 2015 11:50, Vitor George <notifications@github.com>
escreveu:

> O banco de dados foi reiniciado.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codigourbano/cidades-comestiveis/issues/48#issuecomment-118517794>
> .
>



-- 
André Ruoppolo Biazoti
Bacharel em Gestão Ambiental - ESALQ/USP
----------------------------------------------------------
(11)97905791
