### ISSUE TITLE
Acesso aos textos na versão mobile

### ISSUE THREAD

**Issue by andrebiazoti** [codigourbano/cidades-comestiveis#53]
Na versão mobile, não consigo acessar o restante da plataforma (área de textos sobre o que é o projeto, 10 passos pra horta, manifesto etc). Apenas tenho acesso ao mapa. 

Acho que seria interessante abrir os textos no celular também. Há um botão com a cenoura na versão mobile, no canto superior direito, mas ele não faz nada e até atrapalha para fechar a janelas de inserção (ele fica em cima do "x"). 

Acredito que seria bacana esse botão possibilitar o acesso às outras páginas de texto e também possibilitar editar o perfil, além de ser reposicionado para não atrapalhar o fechamento das guias que abrem. O que acham?

**Comment by miguelpeixe** [comment]
adicionei a navegação no mobile para as páginas institucionais mas acho que edição de perfil é algo que ele pode esperar chegar em casa e fazer no computador, o que acha?

**Comment by andrebiazoti** [comment]
Ok! Edição do perfil em casa!
