### ISSUE TITLE
Questão Terrenos X Iniciativas

### ISSUE THREAD

**Issue by andrebiazoti** [codigourbano/cidades-comestiveis#54]
Fiquei refletindo sobre essa questão.

Dentro da perspectiva de considerar iniciativas como hortas já instaladas, o que acham de, quando o terreno é assinalado como "já possui uma horta", ele automaticamente assume o pin da cenoura?

Outra questão é, como será a transição de um terreno ocioso que passa a ser horta? Ele deve ser deletado e reinserido como iniciativa/horta? Ou ele pode ser editado e tornar-se uma iniciativa?

Talvez valha fazermos um skype rapidinho para bater o martelo nesse tema, que tal?

**Comment by miguelpeixe** [comment]
> ele automaticamente assume o pin da cenoura?

sim

> Outra questão é, como será a transição de um terreno ocioso que passa a ser horta? Ele deve ser deletado e reinserido como iniciativa/horta? Ou ele pode ser editado e tornar-se uma iniciativa?

basta editar a area e assinalar o campo referente a horta

**Comment by andrebiazoti** [comment]
Ok!
