### ISSUE TITLE
Desformatação em alguns aparelhos na versão mobile

### ISSUE THREAD

**Issue by andrebiazoti** [codigourbano/cidades-comestiveis#58]
Durante o lançamento ontem, um senhor acessou a plataforma pelo celular e os botões estavam desformatados. O + e a cenoura estavam desalinhados com o círculo laranja. Vocês tem ideia do que pode ter causado?

**Comment by miguelpeixe** [comment]
Pode ser um celular com um sistema antigo. O site utiliza alguns recursos avançados para mobile, só as versões mais recentes suportam.

**Comment by andrebiazoti** [comment]
Ok!
